version: "2.4"

services:
  edge-frontend:
    env_file:
      - ./.docker/.env
    image: edge-frontend
    container_name: edge-frontend
    environment:
      - XDEBUG_HOST=${CONTAINER_HOST_IP}
    build:
      context: ./
      target: edge
      args:
        XDEBUG_ENABLED: "true"
        UID: $USERID
        GID: $GROUPID
        UNAME: $USERNAME
    volumes:
      - ./src:/var/www/
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    user: 1000:1000
    ports:
      - 80:80
      - 5173:5173
    depends_on:
      - edge-database-phpmyadmin

  edge-database:
    container_name: edge-database
    image: percona
    environment:
      MYSQL_USER: edgedb
      MYSQL_PASSWORD: edgedb
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: edge

  edge-database-phpmyadmin:
    container_name: edge-database-phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=edge-database
    depends_on:
      - edge-database
